### ISSUE TITLE
Security vulnerability report

### ISSUE THREAD

**Issue by MarcinHoppe** [prahladyeri/http-live-simulator#3]
I'm a member of the Node.js Foundation Security Working Group and we received a report of a vulnerability in this module.

We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

**Comment by prahladyeri** [comment]
What is the vulnerability?

**Comment by MarcinHoppe** [comment]
It is a denial of service vulnerability. I sent you an e-mail and also invited you to the relevant HackerOne report.

**Comment by prahladyeri** [comment]
Haven't received any email, did you send it to prahladyeri@yahoo.com ?

**Comment by prahladyeri** [comment]
Nor am I seeing anything on my HackerOne inbox.

**Comment by MarcinHoppe** [comment]
Yes, this is the e-mail address I used. I have now re-sent the H1 invite and also sent another e-mail.

**Comment by prahladyeri** [comment]
Hey @marcinhoppe, I've made this fix and published the latest version (v1.0.8) to npm. Please test and let me know.

npm package url: https://www.npmjs.com/package/http-live-simulator
github issue: https://github.com/prahladyeri/http-live-simulator/issues/3
